version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "16:30"
      timezone: Etc/UCT
    reviewers:
      - "nenaraab"
      - "liga-oz"
    open-pull-requests-limit: 10