version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: Etc/UCT
  reviewers:
    - nenaraab
    - InnaAtanasova
  open-pull-requests-limit: 10