---
spring:
  # Runtime Application Name
  application:
    name: xsuaa-usage-sample
  
  # Spring Security Configurations Pointing to XSUAA
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://authentication.eu10.hana.ondemand.com/token_keys
        
# Setting Log Levels          
logging.level:
  com.sap: DEBUG                      # set SAP-class loggers to DEBUG.
  org.springframework: ERROR          # set to DEBUG to see all beans loaded and auto-config conditions met.
  org.springframework.security: DEBUG # set to ERROR for production setups. 
  org.springframework.web: DEBUG      # set to ERROR for production setups.
          
# Server Port (from environment or 8080 if not set).          
server:
  port: ${PORT:8080}

# Enable to make Spring Boot log debug information.
# debug: true  