---
###  SERVICE INSTANCE CONFIGURATION  ###
# Xsuaa instance
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: xsuaa-basic
spec:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: spring-security-basic-auth
    tenant-mode: dedicated
    oauth2-configuration:
      credential-types:
        - x509
    scopes:
      - name: "$XSAPPNAME.Display"
        description: With this scope, information can be read
    role-templates:
      - name: AccessRole
        description: Role to call the spring-security-basic-auth service
        scope-references:
          - "$XSAPPNAME.Display"
    role-collections:
      - name: BASIC_AUTH_API_Viewer
        description: Viewer (read)
        role-template-references:
          - "$XSAPPNAME.AccessRole"
---
apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceBinding
metadata:
  name: xsuaa-basic-binding
spec:
  serviceInstanceName: xsuaa-basic
---
###  APPLICATION CONFIGURATION  ###
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-security-basic-auth
  name: spring-security-basic-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-security-basic-auth
  template:
    metadata:
      labels:
        app: spring-security-basic-auth
        kyma-grafana: enabled
    spec:
      containers:
        - image: <YOUR IMAGE REPOSITORY>
          env:
            - name: SERVICE_BINDING_ROOT
              value: "/bindings"
          imagePullPolicy: Always
          name: spring-security-basic-auth
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: xsuaa-basic
              mountPath: "/bindings/xsuaa-basic"
              readOnly: true
      volumes:
        - name: xsuaa-basic
          secret:
              secretName: xsuaa-basic-binding
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-security-basic-auth
  name: spring-security-basic-auth
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-security-basic-auth
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: spring-security-basic-auth-api
  labels:
    app: spring-security-basic-auth
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: allow
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      path: /.*
  service:
    host: spring-security-basic-auth-api
    name: spring-security-basic-auth
    port: 80