---
###  SERVICE INSTANCE CONFIGURATION  ###
# Xsuaa instance
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: xsuaa-java-security
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServicePlanExternalName: application
  parameters:
    xsappname: xsuaa-java-security
    tenant-mode: dedicated
    scopes:
      - name: "$XSAPPNAME.Read"
        description: "Read Permissions."
    role-templates:
      - name: Viewer
        description: View Data
        scope-references:
          - "$XSAPPNAME.Read"
    role-collections:
      - name: JAVA_SECURITY_SAMPLE_Viewer
        description: Viewer (read)
        role-template-references:
          - "$XSAPPNAME.Viewer"
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: xsuaa-service-binding
spec:
  instanceRef:
    name: xsuaa-java-security
---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: xsuaa-service-binding-usage
spec:
  parameters:
    envPrefix:
      name: xsuaa_
  serviceBindingRef:
    name: xsuaa-service-binding
  usedBy:
    kind: deployment
    name: java-security-usage
---
# Xsuaa broker instance
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: xsuaa-broker
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServicePlanExternalName: broker
  parameters:
    xsappname: xsuaa-broker
    tenant-mode: dedicated
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: xsuaa-broker-binding
spec:
  instanceRef:
    name: xsuaa-broker
---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: xsuaa-broker-binding-usage
spec:
  parameters:
    envPrefix:
      name: xsuaa_
  serviceBindingRef:
    name: xsuaa-broker-binding
  usedBy:
    kind: deployment
    name: java-security-usage
---
# Service manager instance
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: service-manager
spec:
  clusterServiceClassExternalName: service-manager
  clusterServicePlanExternalName: subaccount-admin
  parameters:
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: service-manager-binding
spec:
  instanceRef:
    name: service-manager
---
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: ServiceBindingUsage
metadata:
  name: service-manager-binding-usage
spec:
  parameters:
    envPrefix:
      name: sm_
  serviceBindingRef:
    name: service-manager-binding
  usedBy:
    kind: deployment
    name: java-security-usage
---
###  APPLICATION CONFIGURATION  ###
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-security-usage
    kyma-grafana: enabled
  name: java-security-usage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-security-usage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-security-usage
        kyma-grafana: enabled
    spec:
      imagePullSecrets:
        - name: sap-repo-registry
      containers:
        - image: <placeholder for image repository>
          imagePullPolicy: Always
          name: java-security-usage
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: xsuaa
              mountPath: "/etc/secrets/sapcp/xsuaa/xsuaa-java-security"
              readOnly: true
            - name: xsuaa-broker
              mountPath: "/etc/secrets/sapcp/xsuaa/xsuaa-broker"
              readOnly: true
            - name: service-manager
              mountPath: "/etc/secrets/sapcp/service-manager/sm"
              readOnly: true

      volumes:
        - name: xsuaa
          secret:
              secretName: xsuaa-service-binding
        - name: xsuaa-broker
          secret:
              secretName: xsuaa-broker-binding
        - name: service-manager
          secret:
              secretName: service-manager-binding
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-security-usage
  name: java-security-usage
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-security-usage

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: java-security-api
  labels:
    app: java-security-usage
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: allow
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      path: /.*
  service:
    host: java-security-api
    name: java-security-usage
    port: 80