# SPDX-FileCopyrightText: 2018-2023 SAP SE or an SAP affiliate company and Cloud Security Client Java contributors
# SPDX-License-Identifier: Apache-2.0
---
name: Maven Build main-2.x

env:
  NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

on:
  push:
    branches: [ main-2.x ]
  pull_request:
    branches: [ main-2.x ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 11 ]
    name: Build with Java ${{ matrix.java-version }}

    steps:
      - uses: actions/checkout@v2
      - name: mvn cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-owasp-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-owasp-
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Run integration tests
        run: cd java-security-it; mvn -B package --file pom.xml
      - name: Build java-security-usage
        run: cd samples/java-security-usage; mvn -B package --file pom.xml
      - name: Build sap-java-buildpack-api-usage
        run: cd samples/sap-java-buildpack-api-usage; mvn -B package --file pom.xml
      - name: Build java-tokenclient-usage
        run: cd samples/java-tokenclient-usage; mvn -B package --file pom.xml
      - name: Build java-security-usage-ias
        run: cd samples/java-security-usage-ias; mvn -B package --file pom.xml
