# SPDX-FileCopyrightText: 2018-2021 SAP SE or an SAP affiliate company and Cloud Security Client Java contributors
# SPDX-License-Identifier: Apache-2.0
---
name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B install --file pom.xml --no-transfer-progress
      - name: Run integration tests
        run: cd java-security-it; mvn -B package --file pom.xml --no-transfer-progress
      - name: Build spring-security-basic-auth
        run: cd samples/spring-security-basic-auth; mvn -B package --file pom.xml --no-transfer-progress
      - name: Build spring-security-xsuaa-usage
        run: cd samples/spring-security-xsuaa-usage; mvn -B package --file pom.xml --no-transfer-progress
      - name: Build spring-webflux-security-xsuaa-usage
        run: cd samples/spring-webflux-security-xsuaa-usage; mvn -B package --file pom.xml --no-transfer-progress
      - name: Build java-security-usage
        run: cd samples/java-security-usage; mvn -B package --file pom.xml --no-transfer-progress
      - name: Build sap-java-buildpack-api-usage
        run: cd samples/sap-java-buildpack-api-usage; mvn -B package --file pom.xml --no-transfer-progress
      - name: Build java-tokenclient-usage
        run: cd samples/java-tokenclient-usage; mvn -B package --file pom.xml --no-transfer-progress
      - name: Build java-security-usage-ias
        run: cd samples/java-security-usage-ias; mvn -B package --file pom.xml --no-transfer-progress
      - name: Build spring-security-hybrid-usage
        run: cd samples/spring-security-hybrid-usage; mvn -B package --file pom.xml --no-transfer-progress

